# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R6VKc78ODXCdYRzer8HY0rL82tBQwoSD
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error


# -----------------------------
# 1) File lists (root-level CSVs)
# -----------------------------
air_files = {
    "California": "Air.California.csv",
    "Florida": "Air.Florida.csv",
    "New York": "Air.NewYork.csv",
    "Washington": "Air.Washington.csv",
}

cancer_files = {
    "California": "Cancer.California.csv",
    "Florida": "Cancer.Florida.csv",
    "New York": "Cancer.NewYork.csv",
    "Washington": "Cancer.Washington.csv",
}

os.makedirs("figures", exist_ok=True)


# -----------------------------
# 2) Build annual Avg_AQI per state
# -----------------------------
air_frames = []
for state, path in air_files.items():
    if not os.path.exists(path):
        raise FileNotFoundError(f"Missing file: {path}")

    df = pd.read_csv(path, on_bad_lines="skip")
    df.columns = df.columns.str.strip()

    if "Date" in df.columns:
        df["Date"] = pd.to_datetime(df["Date"], errors="coerce")
        df["Year"] = df["Date"].dt.year
    elif "Year" not in df.columns:
        raise ValueError(f"{path}: expected 'Date' or 'Year' column.")

    if "AQI" not in df.columns:
        raise ValueError(f"{path}: expected 'AQI' column.")

    df["AQI"] = pd.to_numeric(df["AQI"], errors="coerce")
    df["Year"] = pd.to_numeric(df["Year"], errors="coerce")
    df = df.dropna(subset=["Year", "AQI"])
    df["Year"] = df["Year"].astype(int)

    df = df[df["Year"] >= 2010]  # safe filter

    yearly = df.groupby("Year")["AQI"].mean().reset_index()
    yearly.rename(columns={"AQI": "Avg_AQI"}, inplace=True)
    yearly["State"] = state
    air_frames.append(yearly)

df_air = pd.concat(air_frames, ignore_index=True)


# -----------------------------
# 3) Load cancer rate per state
# -----------------------------
cancer_frames = []
for state, path in cancer_files.items():
    if not os.path.exists(path):
        raise FileNotFoundError(f"Missing file: {path}")

    # find header row containing Year + Observed
    with open(path, "r", encoding="utf-8", errors="ignore") as f:
        lines = f.readlines()

    header_row = 0
    for i, line in enumerate(lines):
        if ("Year" in line) and ("Observed" in line):
            header_row = i
            break

    df = pd.read_csv(path, skiprows=header_row, on_bad_lines="skip")
    df.columns = df.columns.str.strip()

    target_col = "Observed"
    if target_col not in df.columns:
        # fallback: try to find Rate/Incidence column
        for col in df.columns:
            if ("Rate" in col) or ("Incidence" in col):
                target_col = col
                break

    if "Year" not in df.columns:
        raise ValueError(f"{path}: expected 'Year' column.")
    if target_col not in df.columns:
        raise ValueError(f"{path}: could not find cancer rate column.")

    df["Year"] = pd.to_numeric(df["Year"], errors="coerce")
    df[target_col] = pd.to_numeric(df[target_col], errors="coerce")
    df = df.dropna(subset=["Year", target_col])
    df["Year"] = df["Year"].astype(int)

    df = df[["Year", target_col]].copy()
    df.rename(columns={target_col: "Cancer_Rate"}, inplace=True)
    df["State"] = state
    cancer_frames.append(df)

df_cancer = pd.concat(cancer_frames, ignore_index=True)


# -----------------------------
# 4) Merge
# -----------------------------
df_final = pd.merge(df_air, df_cancer, on=["State", "Year"], how="inner")
if df_final.empty:
    raise ValueError("Merged dataset is empty. Check overlapping years.")

print("Merged rows:", len(df_final))
print(df_final.head())


# -----------------------------
# 5) ML: Linear Regression (AQI + State)
# -----------------------------
X = df_final[["Avg_AQI", "State"]]
y = df_final["Cancer_Rate"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

pre = ColumnTransformer([
    ("num", "passthrough", ["Avg_AQI"]),
    ("cat", OneHotEncoder(drop="first"), ["State"]),
])

model = Pipeline([
    ("pre", pre),
    ("lr", LinearRegression()),
])

model.fit(X_train, y_train)
pred = model.predict(X_test)

r2 = r2_score(y_test, pred)
mae = mean_absolute_error(y_test, pred)
rmse = np.sqrt(mean_squared_error(y_test, pred))

print("\n=== ML RESULTS (Linear Regression: AQI + State) ===")
print(f"R2   : {r2:.3f}")
print(f"MAE  : {mae:.3f}")
print(f"RMSE : {rmse:.3f}")

# Save metrics
metrics_df = pd.DataFrame([{"Model": "LR (Avg_AQI + State)", "R2": r2, "MAE": mae, "RMSE": rmse}])
metrics_df.to_csv("figures/ml_metrics.csv", index=False)
print("Saved metrics -> figures/ml_metrics.csv")

# Plot predicted vs actual
plt.figure(figsize=(6, 6))
plt.scatter(y_test, pred)
minv = min(float(y_test.min()), float(pred.min()))
maxv = max(float(y_test.max()), float(pred.max()))
plt.plot([minv, maxv], [minv, maxv], linestyle="--")
plt.xlabel("Actual Cancer Rate")
plt.ylabel("Predicted Cancer Rate")
plt.title("Predicted vs Actual (LR: AQI + State)")
plt.tight_layout()
plt.savefig("figures/ml_pred_vs_actual.png", dpi=200)
plt.show()

print("Saved plot -> figures/ml_pred_vs_actual.png")